// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID       int32
	Title    string
	Complete pgtype.Bool
}

type TodoList struct {
	ID        pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}
