// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todos
WHERE id=$1
RETURNING id
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTodo, id)
	err := row.Scan(&id)
	return id, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, complete FROM todos WHERE id=$1 LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int32) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(&i.ID, &i.Title, &i.Complete)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, title, complete FROM todos ORDER BY id DESC
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Title, &i.Complete); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTodo = `-- name: InsertTodo :one
INSERT INTO todos (title) VALUES ($1) RETURNING id, title, complete
`

func (q *Queries) InsertTodo(ctx context.Context, title string) (Todo, error) {
	row := q.db.QueryRow(ctx, insertTodo, title)
	var i Todo
	err := row.Scan(&i.ID, &i.Title, &i.Complete)
	return i, err
}

const updateTodoComplete = `-- name: UpdateTodoComplete :one
UPDATE todos
SET complete = $2
WHERE id = $1
RETURNING id, title, complete
`

type UpdateTodoCompleteParams struct {
	ID       int32
	Complete pgtype.Bool
}

func (q *Queries) UpdateTodoComplete(ctx context.Context, arg UpdateTodoCompleteParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoComplete, arg.ID, arg.Complete)
	var i Todo
	err := row.Scan(&i.ID, &i.Title, &i.Complete)
	return i, err
}
